### ISSUE TITLE
Ability to reuse parts of the original page title in the resulting text

### ISSUE THREAD

**Issue by MurzNN** [gdepourtales/custom-tab-title-favicon#1]
Will be good to add ability to reuse parts of the original page title in resulting generated title.

For example, add some prefix to the original title, or swap the site name and page title on "[site_name] - [page_title]" pages.

This can be implemented using regular expressions for source and replacement string.

**Comment by gdepourtales** [comment]
The version 2 adds the possibility to add dynamic values in the custom title. Please see the [README](https://github.com/gdepourtales/custom-tab-title-favicon/blob/master/README.md) for more details
Version 2 submitted to Mozilla for review
